### ISSUE TITLE
xLib, Celtic3, and DCSB libs not available

### ISSUE THREAD

**Issue by Jeffitus** [KermMartian/Doors_CS_7#2]
When I run det([[42 from a program, it returns 42 instead of 1337, even though TI-Basic libraries are enabled in the options menu. I briefly glanced at the code, but it was not immediately obvious if there was a define or something needed for libraries to work.

**Comment by KermMartian** [comment]
Are you running from the shell or from the homescreen with HomeRun? If you're running from the homescreen, do you get the same result running from the shell?

**Comment by Jeffitus** [comment]
I was using HomeRun, but I just tried and launching directly from the shell produces the same result.

**Comment by KermMartian** [comment]
d48ba7a2789ecea5ccc8b8961511142e711cbba5 fixes this, but I'm really confused how this regression could have occurred. I need to rescue the Mercurial history that's missing before this repo began.
