### ISSUE TITLE
RAM clear in basic programs caused by "Stop" command 

### ISSUE THREAD

**Issue by NinjaWeedle** [KermMartian/Doors_CS_7#3]
I found a bug having to do with using the "Stop" command in any program at any time in these circumstances:

Details: xLib/celtic III/DCS libraries enabled AND Homerun enabled
OS 2.43
Bootcode: 1.03
DCS7.3 running (Runer112 version)

When you run a BASIC program in the TI-stock prgm menu, the calculator will crash and ram clear once  "Stop" runs in any BASIC program.

This only applies with all the libraries above enabled, not an individual library.
This also does not occur when the BASIC program is run from the DCS7 menu.

**Comment by KermMartian** [comment]
@NinjaWeedle have you happened to test if this happens with Doors CS 7.2 as well?

**Comment by NinjaWeedle** [comment]
From my wabbit emu (OS 2.43, DCS7.2) tests, it causes an abnormal screen clear (no done message, essentially a clrhome), but does not crash.
